package com.carbon.repository;

import org.springframework.data.jpa.repository.JpaRepository;
import com.carbon.model.Challenge;
import java.util.List;

/**
 * Repository interface for Challenge entity database operations.
 * Extends JpaRepository which provides CRUD operations (save, findById, findAll, delete, etc.).
 * Spring Data JPA automatically implements this interface at runtime.
 * Custom query methods are auto-generated based on method name conventions.
 */
public interface ChallengeRepository extends JpaRepository<Challenge, Long> {

    /**
     * Finds all challenges with the specified frequency.
     * Used to filter challenges by Daily, Weekly, or Monthly recurrence.
     * @param frequency - "Daily", "Weekly", or "Monthly"
     * @return List of challenges matching the frequency
     * 
     * Implementation auto-generated by Spring Data JPA from method name.
     * Equivalent SQL: SELECT * FROM challenges WHERE frequency = ?
     */
    List<Challenge> findByFrequency(String frequency);
}
