package com.carbon.repository;

import java.time.LocalDateTime;
import java.util.Collection;
import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.Repository;
import org.springframework.data.repository.query.Param;

import com.carbon.model.Challenge;
import com.carbon.model.Evidence;
import com.carbon.model.EvidenceStatus;
import com.carbon.model.DataForAnalytics;
/**
 * Repository interface for Evidence entity database operations.
 * Spring Data JPA automatically implements this interface at runtime.
 * Used by EvidenceService for persisting and retrieving photo evidence submissions.
 */
public interface EvidenceRepository extends JpaRepository<Evidence, Long> {
    /**
     * Finds all evidence submissions with the specified status.
     * Used by moderators to filter pending, accepted, or rejected submissions.
     * @param status - EvidenceStatus enum value (PENDING, ACCEPTED, or REJECTED)
     * @return List of evidence submissions matching the status
     * 
     * Implementation auto-generated by Spring Data JPA from method name.
     * Equivalent SQL: SELECT * FROM evidence WHERE status = ?
     */
    List<Evidence> findByStatus(EvidenceStatus status);

    Collection<DataForProfile> findByUserId(long USER_ID);

    @Query("SELECT e.challenge.points as points, e.submittedAt as submittedAt, e.challenge.taxonomy as taxonomy FROM Evidence e WHERE e.user.id = :userId AND e.status = com.carbon.model.EvidenceStatus.ACCEPTED")
    List<DataForAnalytics> findAcceptedEvidenceByUserId(@Param("userId") long userId);

    /**
     * Checks whether a user has already submitted evidence for a task with the given title
     * within the specified time window.
     */
    @Query("SELECT CASE WHEN COUNT(e) > 0 THEN TRUE ELSE FALSE END FROM Evidence e WHERE e.user.id = :userId AND e.taskTitle = :taskTitle AND e.submittedAt >= :start AND e.submittedAt < :end AND e.status IN (com.carbon.model.EvidenceStatus.PENDING, com.carbon.model.EvidenceStatus.ACCEPTED)")
    boolean hasEvidenceForTaskInWindow(@Param("userId") Long userId, @Param("taskTitle") String taskTitle, @Param("start") LocalDateTime start, @Param("end") LocalDateTime end);

    @Query("SELECT e.status FROM Evidence e WHERE e.user.id = :userId AND e.taskTitle = :taskTitle AND e.submittedAt >= :start AND e.submittedAt < :end AND e.status IN (com.carbon.model.EvidenceStatus.PENDING, com.carbon.model.EvidenceStatus.ACCEPTED) ORDER BY e.submittedAt DESC")
    List<EvidenceStatus> findCompletionStatusesInWindow(@Param("userId") Long userId, @Param("taskTitle") String taskTitle, @Param("start") LocalDateTime start, @Param("end") LocalDateTime end);

    @Query("SELECT DISTINCT e.taskTitle FROM Evidence e WHERE e.user.id = :userId AND e.submittedAt >= :start AND e.submittedAt < :end AND e.status IN (com.carbon.model.EvidenceStatus.PENDING, com.carbon.model.EvidenceStatus.ACCEPTED)")
    List<String> findTodayCompletedTaskTitles(@Param("userId") Long userId, @Param("start") LocalDateTime start, @Param("end") LocalDateTime end);

    long countByUser_IdAndStatus(Long userId, EvidenceStatus status);

    @Query("SELECT COUNT(e) FROM Evidence e WHERE e.user.id = :userId AND e.status = com.carbon.model.EvidenceStatus.ACCEPTED AND e.challenge IS NOT NULL AND e.challenge.requiresEvidence = TRUE")
    long countApprovedEvidenceForBadgeByUserId(@Param("userId") Long userId);

    @Query("SELECT COUNT(e) FROM Evidence e WHERE e.user.id = :userId AND e.status = com.carbon.model.EvidenceStatus.ACCEPTED AND e.challenge IS NOT NULL AND LOWER(e.challenge.frequency) = LOWER(:frequency)")
    long countAcceptedByUserIdAndFrequency(@Param("userId") Long userId, @Param("frequency") String frequency);

    @Query("SELECT COUNT(DISTINCT e.challenge.taxonomy) FROM Evidence e WHERE e.user.id = :userId AND e.status = com.carbon.model.EvidenceStatus.ACCEPTED AND e.challenge IS NOT NULL AND e.challenge.taxonomy IS NOT NULL AND TRIM(e.challenge.taxonomy) <> ''")
    long countDistinctAcceptedTaxonomiesByUserId(@Param("userId") Long userId);

    long deleteByUser_Id(Long userId);

}

interface DataForProfile{
    Challenge getChallenge();
    EvidenceStatus getStatus();
    LocalDateTime getSubmittedAt();
} 
    
