package com.carbon.repository;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;

import com.carbon.model.Evidence;
import com.carbon.model.EvidenceStatus;

/**
 * Repository interface for Evidence entity database operations.
 * Extends JpaRepository which provides CRUD operations for Evidence entities.
 * Spring Data JPA automatically implements this interface at runtime.
 * Used by EvidenceService for persisting and retrieving photo evidence submissions.
 */
public interface EvidenceRepository extends JpaRepository<Evidence, Long> {
    /**
     * Finds all evidence submissions with the specified status.
     * Used by moderators to filter pending, accepted, or rejected submissions.
     * @param status - EvidenceStatus enum value (PENDING, ACCEPTED, or REJECTED)
     * @return List of evidence submissions matching the status
     * 
     * Implementation auto-generated by Spring Data JPA from method name.
     * Equivalent SQL: SELECT * FROM evidence WHERE status = ?
     */
    List<Evidence> findByStatus(EvidenceStatus status);
}
