package com.carbon.repository;

import java.time.LocalDateTime;
import java.util.Collection;
import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.Repository;
import org.springframework.data.repository.query.Param;

import com.carbon.model.Challenge;
import com.carbon.model.Evidence;
import com.carbon.model.EvidenceStatus;
import com.carbon.model.DataForAnalytics;
/**
 * Repository interface for Evidence entity database operations.
 * Spring Data JPA automatically implements this interface at runtime.
 * Used by EvidenceService for persisting and retrieving photo evidence submissions.
 */
public interface EvidenceRepository extends JpaRepository<Evidence, Long> {
    /**
     * Finds all evidence submissions with the specified status.
     * Used by moderators to filter pending, accepted, or rejected submissions.
     * @param status - EvidenceStatus enum value (PENDING, ACCEPTED, or REJECTED)
     * @return List of evidence submissions matching the status
     * 
     * Implementation auto-generated by Spring Data JPA from method name.
     * Equivalent SQL: SELECT * FROM evidence WHERE status = ?
     */
    List<Evidence> findByStatus(EvidenceStatus status);

    Collection<DataForProfile> findByUserId(long USER_ID);

    @Query("SELECT e.challenge.points as points, e.submittedAt as submittedAt, e.challenge.taxonomy as taxonomy FROM Evidence e WHERE e.user.id = :userId AND e.status = com.carbon.model.EvidenceStatus.ACCEPTED")
    List<DataForAnalytics> findAcceptedEvidenceByUserId(@Param("userId") long userId);
}

interface DataForProfile{
    Challenge getChallenge();
    EvidenceStatus getStatus();
    LocalDateTime getSubmittedAt();
} 
    
