package com.carbon.repository;

import org.springframework.data.jpa.repository.JpaRepository;
import com.carbon.model.User;

/**
 * Repository interface for User entity database operations.
 * Spring Data JPA automatically implements this interface at runtime.
 * Central repository used across the application for authentication, points tracking, and user management.
 */
public interface UserRepository extends JpaRepository<User, Long> {
    /**
     * Finds a user by their unique username.
     * Used throughout the application for authentication and retrieving user details.
     * @param username - The username to search for
     * @return User entity if found, null if no user exists with that username
     * 
     * Implementation auto-generated by Spring Data JPA from method name.
     * Equivalent SQL: SELECT * FROM users WHERE username = ? LIMIT 1
     */
    User findByUsername(String username);
}
